### ISSUE TITLE
Step multiplier per cycle isn't working

### ISSUE THREAD

**Issue by Heathen** [aria1th/Hypernetwork-MonkeyPatch-Extension#10]
I set mine to 55 steps per cycle with a multiplier of 1.1 and the step per cycle isn't changing at all. Here's a graph of step:LR

![image](https://user-images.githubusercontent.com/474879/206554902-981aa3cb-559b-41b3-aef0-b7b53b96a6ac.png)

**Comment by aria1th** [comment]
Fixed in https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/commit/f64e7d227c9b07d8ef6a1cf030920115d39efde2 !
Thanks for reporting, previous scheduler only accepted integer, but now it accepts float too, so its fixed.
