### ISSUE TITLE
Traing wont start

### ISSUE THREAD

**Issue by JSarvise** [aria1th/Hypernetwork-MonkeyPatch-Extension#14]
Looks like latest automatic1111 might have broken something cause it was working perfectly for me a few days ago and now it refuses to start after pressing train embedding, normal training works fine if i crop the images to 512x512 but i would prefer a way of making your traing ganma work again.

**Comment by aria1th** [comment]
Can you copy paste some part of the log? Original webui also has some problems, so maybe that https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5280

**Comment by JSarvise** [comment]
I was using runpod so i changed pod already, today it has worked with no problem if it happens again ill try to get some logs but it being a docker limits me in that regard.

**Comment by aria1th** [comment]
I heard that some virtual GPU hosts offers 'fake' vram, so you can't actually run training on those hosts. Maybe that

**Comment by aria1th** [comment]
Closes as https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/commit/022002a916aab33b978e40400513803e9252ffb5
