### ISSUE TITLE
Missing positional argument

### ISSUE THREAD

**Issue by RookieC0der11** [aria1th/Hypernetwork-MonkeyPatch-Extension#18]
hello, everyting was working fine until I got this error message

save_embedding(embedding, checkpoint, embedding_name_every, last_saved_file,
TypeError: save_embedding() missing 1 required positional argument: 'filename'

does the extension crash or something?

**Comment by aria1th** [comment]
Seems like original codebase added optimizer save option, which is maybe identical to my previous pr. I'll implement it.

**Comment by RookieC0der11** [comment]
Thank you aria-sama, I was doing an embed for a client when I get that error, so I just have to wait until you fix it? :^]

**Comment by RookieC0der11** [comment]
Thanks! :D
