### ISSUE TITLE
TypeError: save_embedding() got multiple values for argument 'remove_cached_checksum'

### ISSUE THREAD

**Issue by gLenahan** [aria1th/Hypernetwork-MonkeyPatch-Extension#19]
Attempting to train an embedding always fails, giving this error: 

File "/home/garrett/Desktop/SD/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension/patches/external_pr/textual_inversion.py", line 270, in train_embedding
save_embedding(embedding, optimizer, checkpoint, embedding_name_every, last_saved_file,
TypeError: save_embedding() got multiple values for argument 'remove_cached_checksum'

No amount of changing settings or messing with the .py giving the error fixes the problem. Reinstalling the extension also doesn't fix the issue.

**Comment by Kampfarsch** [comment]
Same issue here.

**Comment by aria1th** [comment]
Can you provide git hash? I confirmed in 9092e1ca7756642692197316d3dec47c23322381, and the function is [same](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/c9bded39ee05bd0507ccd27d2b674d86d6c0c8e8/modules/textual_inversion/textual_inversion.py#L422) in recent version (or main repository will throw same error too)

**Comment by rossturner** [comment]
Same issue for me, could be wrong but I believe on this hash, having installed from github URL

commit 34b969361707f4f8367da6910c4e7c18ae2ed885 (HEAD -> main, origin/main, origin/HEAD)
Author: AngelBottomless <35677394+aria1th@users.noreply.github.com>
Date:   Fri Jan 6 08:17:15 2023 +0900

    Update README.md

**Comment by rossturner** [comment]
D'oh, little behind on the main repository of course. Git pull on stable-diffusion-webui solved it

**Comment by aria1th** [comment]
@gLenahan @Kampfarsch can you try git pull for main repository(webui)? I guess its once messed up and fixed it. Please reopen the issue if it continues.
