### ISSUE TITLE
Using gamma training (pr #4886) error

### ISSUE THREAD

**Issue by sashasubbbb** [aria1th/Hypernetwork-MonkeyPatch-Extension#2]
All default settings error from the first step in HN gamma training 
![ss+(2022-11-24+at+02 28 39)](https://user-images.githubusercontent.com/60400449/203774207-c0e33826-cc37-44aa-9a46-2dc907782f2c.png)

**Comment by aria1th** [comment]
It happens when inf or NaN value is encountered while training, can you try beta training instead? seems like there's issue with grad_scaler maybe...
Try updating Extension to the most recent version, and please check if issue remains

**Comment by sashasubbbb** [comment]
Fixed in latest update, thank you
