### ISSUE TITLE
Missing positional argument filename

### ISSUE THREAD

**Issue by amarney4862** [aria1th/Hypernetwork-MonkeyPatch-Extension#20]
I got an error while trying to train an embed which seems similar to #18.

the file is \patches\external_pr\textual_inversion.pv, line 223, in train_embedding
TypeError: save_embedding() missing 1 required positional argument: 'filename'

**Comment by aria1th** [comment]
Seems like you're using unmatched versions, well webui had some changes, and I fixed it recently too. Try updating both extension and webui (by git pull)

**Comment by amarney4862** [comment]
I did try that before, but closing/restarting webui after updating both fixed the issue. Thanks!
