### ISSUE TITLE
[Request] Implement "Use CosineAnnealingWarmupRestarts Scheduler" for embedding training

### ISSUE THREAD

**Issue by Zyin055** [aria1th/Hypernetwork-MonkeyPatch-Extension#21]
Currently this advanced learning rate scheduler is only available for hypernetworks. It would be nice if it was also implemented for training embeddings.

**Comment by aria1th** [comment]
Please check if its working correctly, I just did some basic test for functionality.

**Comment by Zyin055** [comment]
Doesn't appear to be working. It's still using the default learn rate of 0.005.

![Clipboard01](https://user-images.githubusercontent.com/5003647/211609805-477c2e53-e648-47ef-bce1-e03d641768a7.jpg)

![Clipboard02](https://user-images.githubusercontent.com/5003647/211609808-2e4c085e-3b5b-4b58-9b53-0233c20dde13.jpg)

**Comment by Zyin055** [comment]
Tried again on 1/19/22, this is still not working for embeddings. Requesting to reopen this issue.
