### ISSUE TITLE
Cant train

### ISSUE THREAD

**Issue by voreman567** [aria1th/Hypernetwork-MonkeyPatch-Extension#25]
So ive been trying to create a hypernetwork for a character. When I create the hypernetwork it does that just fine, but when I start to try and train it, it gives me this error:
---------------------------------------------------------------------------------------------------------------------------------------
[1.0, 2.0, 1.0]
Activation function is linear
Weight initialization is Normal
Layer norm is set to False
Dropout usage is set to True
Activate last layer is set to False
Dropout structure is set to [0, 0.3, 0]
No saved optimizer exists in checkpoint
Training at rate of 5e-05 until step 2500
Preparing dataset...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 25.66it/s]
Applying cross attention optimization (Doggettx).
Error completing request
Arguments: ('Hypernetwork name(12345abcd)', '0.00005', 1, 1, 'imagetraining\\Processed character images', 'textual_inversion', 512, 512, 2500, 'disabled', '0.1', True, 0.3, 'deterministic', 50, 50, 'textual_inversion_templates\\hypernetwork.txt', True, 'tag1, tag2, tag3,  ', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "stable-diffusion-webui\modules\hypernetworks\ui.py", line 27, in train_hypernetwork
    hypernetwork, filename = modules.hypernetworks.hypernetwork.train_hypernetwork(*args)
  File "stable-diffusion-webui\modules\hypernetworks\hypernetwork.py", line 480, in train_hypernetwork
    hypernetwork.train_mode()
AttributeError: 'Hypernetwork' object has no attribute 'train_mode'
--------------------------------------------------------------------------------------------------------------------------------------------------

If anyone here can help me, it would be appreciated. Thanks.

**Comment by aria1th** [comment]
You need to restart UI(close cmd and restart), also try updating both main repository and extension.

**Comment by voreman567** [comment]
This initially worked, but when I was testing, I was able to retrain the same hypernetwork. Like after its first training, id go into the files pick an image I liked then picked its corresponding .pt file, like hypernetwork-3000.pt then retrain that. It would work just fine, but now when I try to retrain my new hypernetwork, it just doesn't work. I put whatever ,pt file I like into the hypernetworks folder, restart the program, then reenter settings and tweak the learning with an extra 0, and I cant resume/retrain the hypernetwork after it's initial training. Do you know why? I get no error messages. It just gives me the settings in the cmd of the hypernetwork, then on the ui it says hypernetwork-3000 trained in X amount of steps.

**Comment by aria1th** [comment]
The most likely mistake is this:
![image](https://user-images.githubusercontent.com/35677394/212520074-e7414b7a-3e63-4ef8-bd57-308fc42cead7.png)

I'm checking if there's any optimizer related issue.

**Comment by voreman567** [comment]
The learning rate schedule is the hypernetwork learning rate right? 
![image](https://user-images.githubusercontent.com/81208275/212598812-5b83a81a-80b3-4caa-8dfe-2b3581e601c2.png)
This is what I have it set to for 2nd time training it. the first is just one less 0. But my steps are also under 100000 (I used 3000 steps after the first training of 5000 steps.) I've tried multiple methods in training and changing settings but still cannot get it to retrain and continue to get the error, even when I try to retrain my test batches that I know were able to be retrained before.

**Comment by aria1th** [comment]
That value is too small, but it should work. But you need to make step bigger than current hypernetwork step, it does not mean 'step to train', its 'final step that is summed for hypernetwork. 

In CMD, you should see `Model has already been trained beyond specified max steps` if its stopping from step count. Otherwise, it should throw RuntimeError or `Error` with code snippet.

**Comment by aria1th** [comment]
It depends, but using extension - with normal weight initialization, you can even use big learning rate such as 0.0007. 
But usually it depends - with weight initialzation and your hypernetwork structure... so I suggest doing some 'short' test with preview, then check the trend, make learning rate higher until its significant.
