### ISSUE TITLE
What does "supports multiple hypernetworks" mean?

### ISSUE THREAD

**Issue by ClashSAN** [aria1th/Hypernetwork-MonkeyPatch-Extension#26]
hi @aria1th, in the wiki you say: "supports multiple hypernetworks." I'm not sure what it means, is it related to training/merging?

A second extension applies multiple hypernetworks on a picture when using: https://github.com/antis0007/sd-webui-multiple-hypernetworks

**Comment by bananasss00** [comment]
You can create a text file with hns extension and place it in the directory with your hypernetwork models. Can then be selected as a hyper model this file

Hns file is designed to use several models at the same time with different strength values.

Read more here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4334

**Comment by aria1th** [comment]
Its very old feature, actually that extension was based on my patch.
![image](https://user-images.githubusercontent.com/35677394/212292727-615e9fe4-275f-4a0b-af1c-961b14219a55.png)

You can create `.hns` file that defines order and mix ratio of hypernetworks. for example here, haibara_2177_1089 is .hns file that is created with notepad
```
[('haibara_mish-1089', 0.5), ('haibara_without_desc-2177', 0.5)]
```

This means you'll apply first hypernetwork with strength 0.5, then apply second hypernetwork with strength 0.5.

In mathematical representation,

`R(x) = B(A(x, 0.5), 0.5)`



To 'mix', weighted sum, you can define as this :

![image](https://user-images.githubusercontent.com/35677394/212293569-a6056b75-4377-4787-9d74-5bd0b6050a8e.png)


Here, haibara_ai_st is defined as

```
{'haibara_mish-1089': 4, ('Tamano_Kedama-gamma', 0.15): 1}
```

This means first hypernetwork will be applied with strength 1.
Second hypernetwork will be applied with strength 0.15.

Both result will be 'mixed' by weight 4:1.

In mathematical representation, 

`R(x) = {4*A(x, 1) + 1*B(x, 0.15) }/ 5`

[haibara_2177_1089.txt](https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/files/10410448/haibara_2177_1089.txt)
[haibara_ai_st.txt](https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/files/10410449/haibara_ai_st.txt)

You can just change .txt file to .hns file. That's all!

**Comment by ClashSAN** [comment]
It seems like you mean for training.

- allows processing multiple HN sequentially, or in parallel.
- order and mix ratio of hypernetworks.

**Comment by ClashSAN** [comment]
ah, i see you're editing it, ty

**Comment by ClashSAN** [comment]
>Its very old feature, actually that extension was based on my patch.

>A second extension applies multiple hypernetworks on a picture when using: https://github.com/antis0007/sd-webui-multiple-hypernetworks

now i re-read it again and it sounds like for inference.
anyhow, please.. if I'm wrong, edit the extension wiki and extensions index to say for inference, training, or both if that's what it is.

**Comment by aria1th** [comment]
Yes, its for inference. Actually training can somehow actually work with hns file, (although there is no proper 'save' function currently) without any problem, but I don't plan to really allow it.
