### ISSUE TITLE
[Question] What res am I supposed to choose when im not cropping images

### ISSUE THREAD

**Issue by Lukxie** [aria1th/Hypernetwork-MonkeyPatch-Extension#3]
I assume the preprocess must be done outside the UI but what about the resolution, is it forcing the resolution to fit on the images or is it loading them as the res they are. Clarify. Also a tab to just deepboru your images would be pretty sweet considering the extension can train without cropping.

**Comment by aria1th** [comment]
Its loading image itself without forcing resizing, but if it exceeds given size (i.e. 512x512 with option), then it will resize it, but respects its ratio. 
If image size was smaller than 512x512, then it will use itself. (240x320 then 240x320)

If image size is bigger than 512x512, then it will resize. (1024x768 -> 512x384 resize)

Thus you don't have to pick resolution.

**Comment by Lukxie** [comment]
Thanks for the answer
