### ISSUE TITLE
Question - No-Crop Training

### ISSUE THREAD

**Issue by msampson3d** [aria1th/Hypernetwork-MonkeyPatch-Extension#31]
Sorry, this isn't an issue but there is no discussion tab and was looking for some clarification on this feature: No-Crop training. 

Is the reason you don't need to crop your images because they are cropped on the fly by your extension, or is there some implementation of bucketing that allows the images to be trained at their given non-square aspect ratios?

If it's using bucketing, what are the width and height sliders doing on the training_gamma tab?

**Comment by dill-shower** [comment]
https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/issues/3

**Comment by msampson3d** [comment]
Closing as that generally answers my questions. Thanks!
