### ISSUE TITLE
AttributeError: module 

### ISSUE THREAD

**Issue by RookieC0der11** [aria1th/Hypernetwork-MonkeyPatch-Extension#36]
hello sir, i just update your extension and I get this error, also it is imoeding my webui to work at all

 File "C:\Users\USER\Downloads\stable\stable-diffusion-webui\extensions\Hypernetwork-MonkeyPatch-Extension\patches\hypernetwork.py", line 483, in load_hypernetwork
    if shared.loaded_hypernetwork is not None:
AttributeError: module 'modules.shared' has no attribute 'loaded_hypernetwork'. Did you mean: 'loaded_hypernetworks'?

**Comment by mykeehu** [comment]
Automatic has reworked the basics of hypernetwork in version 40ff6db5325fc34ad4fa35e80cb1e7768d9f7e75, which is better in many ways, but you need to rewrite this extension.

**Comment by aria1th** [comment]
I'm working on it, but it may take few hours

**Comment by aria1th** [comment]
I'm pretty sure original webui's training feature is broken if preview option is enabled...
half a way done

**Comment by aria1th** [comment]
Currently, its available at https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/tree/latest-fix
But since I have to check compatibility with previous webui version too, merge will happen after testing all features.
