### ISSUE TITLE
Sometimes training stops a step before generating preview/embedding

### ISSUE THREAD

**Issue by RevyaM** [aria1th/Hypernetwork-MonkeyPatch-Extension#43]
Pretty much the title.
It happens randomly after embedding was being trained for some time (the least amount of steps before this happening was 149, I think; the most was 1649). I'm using pretty much the same settings every single time: 
LR: 0.0005
Batch: 1
Grad: 5
Save preview/model: 50 steps
Latent sampling method: once

The thing was working just fine with those settings a week ago, but now it gives this error: 

[Epoch 94: 8/18]loss: nan:  66%|███████████████████████████████████▏                 | 199/300 [07:34<03:34,  2.12s/it]Traceback (most recent call last):██████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.29it/s]
  File "D:\SD\extensions\Hypernetwork-MonkeyPatch-Extension\patches\external_pr\textual_inversion.py", line 368, in train_embedding
    save_embedding(embedding, optimizer, checkpoint, embedding_name_every, last_saved_file,
  File "D:\SD\modules\textual_inversion\textual_inversion.py", line 645, in save_embedding
    embedding.save(filename)
  File "D:\SD\modules\textual_inversion\textual_inversion.py", line 69, in save
    'hash': self.checksum(),
  File "D:\SD\modules\textual_inversion\textual_inversion.py", line 84, in checksum
    self.cached_checksum = f'{const_hash(self.vec.reshape(-1) * 100) & 0xffff:04x}'
  File "D:\SD\modules\textual_inversion\textual_inversion.py", line 81, in const_hash
    r = (r * 281 ^ int(v) * 997) & 0xFFFFFFFF
ValueError: cannot convert float NaN to integer

The training can be continued, but will do the same error once it reaches the saving step (no matter if it's a preview or a model). After this error occurs, it would become unusable in image generation. The error: 
Traceback (most recent call last):
  File "D:\SD\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\SD\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\SD\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\SD\modules\processing.py", line 484, in process_images
    res = process_images_inner(p)
  File "D:\SD\modules\processing.py", line 626, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\SD\modules\processing.py", line 826, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\SD\modules\sd_samplers_kdiffusion.py", line 290, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\SD\modules\sd_samplers_kdiffusion.py", line 190, in launch_sampling
    return func()
  File "D:\SD\modules\sd_samplers_kdiffusion.py", line 290, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\SD\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\SD\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SD\modules\sd_samplers_kdiffusion.py", line 111, in forward
    devices.test_for_nans(x_out, "unet")
  File "D:\SD\modules\devices.py", line 157, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

**Comment by aria1th** [comment]
Mainly, when you encounter NaN, there's 3 possibilities:
1. Exploding gradient problem - its very 'steep' casse.
2. Token embedding is not used in your training step. mainly, it happens when you use improper template, like template that does NOT invoke your token. i.e. if your token is 'asdf', then asdf should be inside of your all templates, in any form.
3. Precision error, unlikely, but can happen when devices are not matching.

if it happens 'sometimes', then I'm not really sure about it...  but most likely case is second one. Please check if template is valid before training.

**Comment by RevyaM** [comment]
> Mainly, when you encounter NaN, there's 3 possibilities:
> 
> 1. Exploding gradient problem - its very 'steep' casse.
> 2. Token embedding is not used in your training step. mainly, it happens when you use improper template, like template that does NOT invoke your token. i.e. if your token is 'asdf', then asdf should be inside of your all templates, in any form.
> 3. Precision error, unlikely, but can happen when devices are not matching.
> 
> if it happens 'sometimes', then I'm not really sure about it... but most likely case is second one. Please check if template is valid before training.

My template used is just 45 lines of "[filewords], art by [name]".

**Comment by aria1th** [comment]
is there certain steps to make it 100% fail?

**Comment by aria1th** [comment]
with high possibility, its exploding gradient, you can try 'gradient clip' that might solve some problems.

**Comment by RevyaM** [comment]
I will try training a version of an embedding which "exploded" a few steps behind it with the same settings and, if it explodes again, with the gradient clip.

**Comment by RevyaM** [comment]
UPD: I've trained that very embedding that got destroyed 50 steps before that happened. 
It did pass the previous mark and trained up to 2000th step without any problems. Seems like it really is just random.

**Comment by aria1th** [comment]
Its exploding gradient problem, loss diverges to infinite(NaN, not a number).
For complex-multidimensional convex problem, its very common. And for this case, its 'eventual', Every Adam, or momentum based optimizer would make loss diverge to NaN since it premises the existence of 'better' local minimum.

In other worlds, AdamW optimizer might have found some good point. But, it won't stop or converge there. Instead, it will try to stand there for a short moment, then tries to jump, to find even better point.

If function space is 'simply convex', then AdamW will eventually return to global mimina, but usually, it could fail to find better local minima, and even diverge.

**Comment by RevyaM** [comment]
Well, that could be it, I guess I'll just keep making 50 step saves in case something like that happens.
