### ISSUE TITLE
AssertionError: Dropout Sequence should start and end with probability 0!

### ISSUE THREAD

**Issue by Notloc** [aria1th/Hypernetwork-MonkeyPatch-Extension#46]
Networks can be trained that break this rule through the default UI, this prevents them from being used to generate images when this extension is installed.

**Comment by aria1th** [comment]
Can you upload the specific hypernetwork?

**Comment by Notloc** [comment]
Looks like you've fixed it already by changing to a warning.
The webUI is recommending this setup by default so it's likely how many people have created networks.
![image](https://user-images.githubusercontent.com/23246298/219564734-1325035a-9ae3-407c-82eb-55c40738b92c.png)
