### ISSUE TITLE
When should we use train_tuning?

### ISSUE THREAD

**Issue by HeavyTony2** [aria1th/Hypernetwork-MonkeyPatch-Extension#49]
Is there a specific reason to use train_tuning instead of train_gamma? Are they suppose to represent to different steps or tuning can be used to continue a previously interrupted training?

**Comment by bananasss00** [comment]
for test any train settings or model structure in batch

**Comment by aria1th** [comment]
its for comparing multiple settings. I recommend using tensorboard with it.

For example, you can create settings file for hypernetworks, like hypernetwork with / without dropout.

Then, you can create settings file for training, like with cosine annealing / without it.

With train_tuning tab, you can test combinations of them automatically, then observe the result with tensorboard.
For example, the image below is comparision between 'noise scheduler' option.


![image](https://user-images.githubusercontent.com/35677394/222822380-9e04e967-c5bc-4da6-a707-9397e198dd3d.png)


Of course, you can do other stuff like comparing between activation functions, hypernetwork structures, etc.

Unfortunately, currently it only supports hypernetwork training - when I have time, I'll do same stuff for textual inversion.
