### ISSUE TITLE
Error after starting training

### ISSUE THREAD

**Issue by sashasubbbb** [aria1th/Hypernetwork-MonkeyPatch-Extension#5]
![ss+(2022-11-27+at+12 09 10)](https://user-images.githubusercontent.com/60400449/204127470-24b90bbe-30bf-4945-98f4-b158b47abb54.png)
All default settings

**Comment by aria1th** [comment]
Fixed in https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension/commit/6e883155900398afadaa19cf22629ef4bcefd26e
