### ISSUE TITLE
Using uncropped images leads to stretched or squashed down outputs

### ISSUE THREAD

**Issue by sashasubbbb** [aria1th/Hypernetwork-MonkeyPatch-Extension#8]
Don’t know if this is only an issue on my side, but it seems after some training has been done the hypernetwork outputs get “squashed down” because of uncropped imgs inputs. I have a feeling it only happens when the aspect ratio of individual input images are beyond 2:1 or 1:2, though this is only me guessing.

**Comment by aria1th** [comment]
![image](https://user-images.githubusercontent.com/35677394/205610557-2896e0d8-2069-44d0-be5a-2e79d4fb43cf.png)
If you're setting is like this, and without extension, its expected. With extension, it could still happen when its image has to be resized severely.

The rule of no-cropping works like this : With setting 512x512, the longer side of the image gets resized to match 512. The other side uses 'ratio' to be resized.
But if you have super long image like 16384x512, then it will be distorted severely, resizing could not help anything. Those type of images are forced to 512x16, which is not even recognizable. If you're using too long images, maybe from manga, it is suggested to split up those images.
